### PR TITLE
handle CTRL-D out

### PR DESCRIPTION
**Pull request by brianshumate**
handle a CTRL-D at the prompt

### CODE REVIEW

**Comment by shaneriley** [comment]
Looks like you accidentally committed your save game in data.json.

**Comment by SwartzCr** [comment]
also probably don't actually need to be importing sys

**Comment by SwartzCr** [comment]
a smarter me would like to come up with a git commit hook that re-generates the levels

**Comment by SwartzCr** [comment]
anyway since I made a merge conflict for you I just added this separately
https://github.com/SwartzCr/katamari/commit/0b10809a769e140741655d3de20022cf7109db2a
sorry, but also thanks!

**Pull request closed without merging**
