### PR TITLE
Fix spelling of 'papar'

### PR DESCRIPTION
**Pull request by shaneriley**

### CODE REVIEW

**Comment by SwartzCr** [comment]
it's impossible to tell what actually got changed since the JSON is all on one line.
I'm going reformat it, and then you should re-submit this PR when it's diffable

**Comment by SwartzCr** [comment]
Oh but actually it should just be changed in the levels.py file and then those should be regenerated

**Comment by SwartzCr** [comment]
this has been fixed in https://github.com/SwartzCr/katamari/commit/c863c980a1839d242e7b40977e92fd69fb60332f
you'll see that this line in levels.py has been changed: https://github.com/SwartzCr/katamari/commit/c863c980a1839d242e7b40977e92fd69fb60332f#diff-06daf57ddf31a096ca6a59dd3ea30200L14
which gen_game.py uses to generate the level data. I would highly recommend not mucking around with the json files themselves, because that's just going to lead to madness (and get overwritten when something is generated)

**Comment by shaneriley** [comment]
Ah! I had no idea it was generated. Makes sense, though. I noticed it while playing and just did a global regex replace. Thanks!

**Comment by SwartzCr** [comment]
No worries, feel free to keep opening PRs or issues though!

**Pull request closed without merging**
